### ISSUE TITLE
Small problem in evaluating TinyBERT on Chinese tasks

### ISSUE THREAD

**Issue by lengfeng343** [bo-sfl/TinyBert#2]
Have you evaluated TinyBERT on the Chinese task? Can you share the general distilled TinybERT, or share the wiki data of Chinese in the general training?

**Comment by bo-sfl** [comment]
@lengfeng343 I never used it for Chinese task and this code base was mainly a copy over from TinyBert's official release. Please checkout their repo at https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/TinyBERT

**Comment by lengfeng343** [comment]
OK, thanks!
